---
name: Tests - Lua

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  job:
    name: Run Lua Tests
    runs-on: ubuntu-latest

    steps:
      - name: Update
        run: sudo apt-get update

      - name: Setup Lua
        run: sudo apt-get install -y libluajit-5.1-dev

      - name: Check out code.
        uses: actions/checkout@main
